### ISSUE TITLE
displayed:false on visible elements

### ISSUE THREAD

**Issue by zolrath** [selenide/selenide#201] opened 2015-07-26 05:58 UTC
Hi! While testing the Selenide API I found a case using the default Firefox Driver (using Firefox 39.0 on OS X Yosemite) where a plainly visible element on the page fails to be interacted with as Selenide believes it isn't displayed.

```
! com.codeborne.selenide.ex.ElementShould: Element should be visible {By.name: session[username_or_email]}
! Element: '<input autocomplete="on" class="js-username-field email-input js-initial-focus" name="session[username_or_email]" type="text" displayed:false></input>'
```

gets thrown when the following code is run:

```
open("https://twitter.com/login/");
$(By.name("session[username_or_email]")).val("name");
$(By.name("session[password]")).setValue("password");
$(".submit").click();
```

**Comment by asolntsev** [comment] 2015-07-26 07:00
@zolrath The problem is that there is 3 such fields on the page.

Try to add the following line to your test:
```java
$$(By.name("session[username_or_email]")).shouldHave(size(1));
```

Then you will get the folloing error:

```java
ListSizeMismatch : expected: 1, actual: 3, collection: By.name: session[username_or_email]
Elements: [
	<input autocomplete="on" class="js-username-field email-input js-initial-focus" name="session[username_or_email]" type="text" displayed:false></input>,
	<input autocomplete="on" class="js-username-field email-input js-initial-focus" name="session[username_or_email]" placeholder="Phone, email or username" type="text"></input>,
	<input autocomplete="on" class="text-input email-input" id="signin-email" name="session[username_or_email]" placeholder="Phone, email or username" type="text" displayed:false></input>
]
```

There is another feature request that addresses the same problem: https://github.com/codeborne/selenide/issues/129

Thank you for reporting a very easy example (Twitter). I will use it for implementing issue https://github.com/codeborne/selenide/issues/129.

**Comment by zolrath** [comment] 2015-07-26 18:03
Thanks for the quick response! 
`$$(By.name("session[username_or_email]")).filter(visible).get(0).setValue("name");` was my workaround in this case.

**Comment by cunhanohaole** [comment] 2016-01-19 01:29
I am facing the same error and my page definetly does not have more than one field with the same id.

Any idea what else could be causing this?

I am trying to select a check box by id and it says it is not visible...

**Comment by asolntsev** [comment] 2016-01-19 05:20
Hi!
Can you code sample and html?

**Comment by stupchiy** [comment] 2016-03-07 14:26
@asolntsev I have the same issue currently and it is also, the same as from last commented, not connected with more than one element with the same id.

Initially I had PageObject with defined element using @FindBy:
```
@FindBy(id = "_portlet_currencyWorldwideCheckbox")
private SelenideElement allowAnyCurrencyCheckbox;
```
And was getting error when trying to `allowAnyCurrencyCheckbox.setSelected(true)`:
```
Element should be visible {By.id: _portlet_currencyWorldwideCheckbox}
Element: '<input class="aui-field-input aui-field-input-choice icheck-input icheck[svz0a]" id="_portlet_currencyWorldwideCheckbox" name="_portlet_currencyWorldwideCheckbox" onclick="Liferay.Util.updateCheckboxValue(this); currenciesjsp_changeWorldwide(this);" type="checkbox" value="*" selected:true displayed:false></input>'
```
Was trying the same with `$(By.id("_portlet_currencyWorldwideCheckbox")).click()` or `$(By.id("_portlet_currencyWorldwideCheckbox")).setSelected(true)` - outcome "not changed"

I experimented a bit, and seems it happens on stage of wrapping WebElement to SelenideElement, you should know better, and when it marks it with **displayed:false**. We have a bit messy pages there, they are jsp's with JavaScript and jQuerry, but you actually could interact with that element, if you use WebElement of Webdriver, so as example this would work: 
`$(By.id("_portlet_currencyWorldwideCheckbox")).toWebElement().click()`

So the problem, when I call SelenideElement to perform some action with it, but seems it is already rely on **displayed:false**, right?

Here more html snippet of the element and parents:
```
<div class="row">
  <div class="col-md-6"> 
    <span class="aui-field aui-field-choice"> 
      <span class="aui-field-content"> 
        <span class="aui-field-element aui-field-label-right"> 
          <input id="_portlet_currencyWorldwide" name="_portlet_currencyWorldwide" type="hidden" value="&#x2a;" /> 
          <input checked class="aui-field-input aui-field-input-choice"  id="_portlet_currencyWorldwideCheckbox" name="_portlet_currencyWorldwideCheckbox"  onClick="Liferay.Util.updateCheckboxValue(this); currenciesjsp_changeWorldwide(this);"  type="checkbox" value="&#x2a;"   /> 
        </span>
        <label class="aui-choice-label" for="_portlet_currencyWorldwideCheckbox"> The provider allows any currency. </label>
      </span>
    </span>
  </div>
</div>
```

Let me know if you need more info from me...

**Comment by asolntsev** [comment] 2016-05-09 22:21
@stupchiy sorry for the long reply. 
I tried your example, and it worked for me. I don't think there could be any difference between WebElement and SelenideElement. 

Probably it's just a timing issue. 
Look, the error message clearly says "Element should be visible" - this means that **at that moment** the element was invisible.

**Comment by stupchiy** [comment] 2016-05-10 08:08
@asolntsev no worries about delay, thanks for reply in any case.
Well, I am sure it's not about timing, since it is not trying to perform that action before all elements loaded (tried with different delay's), my suspicion was that **displayed:false** not always properly set. 
And also as I mentioned, when you try to perform `$(By.id("_portlet_currencyWorldwideCheckbox")).click()` or `$(By.id("_portlet_currencyWorldwideCheckbox")).setSelected(true)`, when element is definitely loaded, it is not perform those action's. 
Anyway thanks again, that took time to look into it.

**Comment by Bogdkad** [comment] 2016-05-13 18:48
@asolntsev @stupchiy 
I just came across the same issue. And I think this could be a Selenium WebDriver issue, rather then a Selenide one.
I check a certain group of elements in my page for visibility, then some changes are made to the page and these elements should still be visible. And they are, but Selenide reports they are not, inserting **displayed:false** into the element. Basically, these are the same elements as in the first case, but for some reason they become invisible to Selenide.

```
Element should visible {.additional-navigation .help-block a}
Element: '<a class="blue-link" href="/login" target="_blank" displayed:false></a>'
```

And in my case it's certainly not the timing issue - I used debug mode to make sure the elements are properly loaded. I used css selectors and selector byText to locate the elements, the latest version of Selenide.
I tried to rewrite my check like this 
`assertThat(WebDriverRunner.getWebDriver().findElement(By.cssSelector(".blue-link")).isDisplayed()).isTrue();`

and I am still getting an error, since isDisplayed() returns false, when elements are clearly visible.

**Comment by thasherwin** [comment] 2016-05-13 19:10
I had this issues also and used javascript as a workaround to click on the checkbox. Would be nice if there will be a solution

**Comment by FrameBassman** [comment] 2017-08-24 13:33
I have the same issue in my code - I find element by Id, click on it and have 'Element should be visible' error message. Also use javascript click as a workaround.
Any chance that this ticket will be reopened?

**Comment by asolntsev** [comment] 2017-08-30 22:11
@FrameBassman Sure, I have reopened the issue. I need to investigate your code with html.

**Comment by asolntsev** [comment] 2017-08-31 16:36
@FrameBassman Please also provider your Java code that fails.

**Comment by FrameBassman** [comment] 2017-09-01 13:46
@asolntsev Java code is here https://gist.github.com/FrameBassman/cca80bb6c52ea34eb1dc70d82930f09f

**Comment by asolntsev** [comment] 2017-09-05 15:32
@FrameBassman Thank you! I will research it in details,
but at a first glance, Selenium thinks that this element is not visible. Do you know why? Probably it has some magic CSS properties? Is it really visible to users?

**Comment by lminiailo** [comment] 2017-10-11 14:04
@FrameBassman , I faced the same issue. Try XPath locator. It works for me :)

**Comment by sadsridh** [comment] 2017-10-17 19:37
I had the same issue for a Oracle Jet checkbox and i tried the workaround by @stupchiy  
$(Locator).toWebElement().click() it works now !

**Comment by SEMrushQA** [comment] 2017-11-01 19:01
```
//selenide code
public Page closeWindow(){
        if ($("button.close").is(Condition.visible)){ // .isDisplayed() or .isEnabled() - the same result
            $("button.close").click();
        }
        return this;
    }
```
Element should be visible {button.close}
Element: '<button class="close" displayed:false></div>'

When button is visible - works fine. But when it's hidden - nope.

**Comment by thereiskeks** [comment] 2018-10-18 07:19
Is there any progress on this? I also have the error and always using xpath is annoying.

**Comment by asolntsev** [comment] 2018-11-02 22:40
@thereiskeks @SEMrushTasks @sadsridh @lminiailo I investigated this problem once more and found that this element has CSS property `opacity: 0`. For Selenium it means that the element **is not visible**. But Selenide method `$.click()` only allows to click visible elements.

We probably should change `$.click()` implementation so that it also allowed clicking invisible elements (like this one with `opacity: 0`). 

@BorisOsipov @rosolko @symonk @vinogradoff  What do you think?

**Comment by asolntsev** [comment] 2018-11-21 21:49
@gedankennebel We are discussing a better method name in PR https://github.com/selenide/selenide/pull/851

**Comment by sadsridh** [comment] 2018-12-19 15:57
Thanks @asolntsev this addresses a lot of failures due to ElementNotVisible errors.

**Comment by sadsridh** [comment] 2019-03-11 18:02
hi,
I upgraded to selenide 5.2.0 and still see this issue with elements having zero opacity.
From the changelog for Selenide version 5.1.0 which says this is fixed..
#201 can click elements with zero opacity -- thanks to @vinogradoff for PR #874

**Comment by asolntsev** [comment] 2019-03-11 18:06
@sadsridh Yes, it should be fixed.
Can you provide html code and exact error message with full stack trace?

**Comment by sadsridh** [comment] 2019-03-11 18:14
```Element should have visible {button#exclude-editButton}
Element: '<button aria-label="Edit the list" class="oj-button-jqui oj-button oj-component oj-enabled oj-default oj-button-full-chrome oj-button-text-only oj-component-initnode" data-bind="
    attr: {
      id: id + '-editButton',
    'aria-label': $root.resource('ns.common:resources.ariaLabelEditListEditButton')
    },
    ojComponent: {
      component: 'ojButton',
      label: $data.isViewButton() ? 'View' : $root.resource('ns.common:resources.editButton')
    },
    click: onEdit,
    enable: enabled" id="exclude-editButton" type="submit" displayed:false></button>'

Screenshot: file:/D:/.../uitests/admin/build/reports/tests/1552326455484.0.png
Page source: file:/D:/.../uitests/admin/build/reports/tests/1552326455484.0.html
Timeout: 10 s.
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:72)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at controls.admin.modules.AdminModule.scrollIntoView(AdminModule.groovy:244)
	at .controls.admin.modules.IXEditorModule.openModalForAdd(IXEditorModule.groovy:233)
	at controls.admin.modules.IXEditorModule.addItemsToPromotion(IXEditorModule.groovy:37)
	at controls.admin.modules.PromotionModule.setPromotionProperties(PromotionModule.groovy:386)
	at controls.admin.modules.PromotionModule.editPromotion(PromotionModule.groovy:319)
	at uitest.spec.promotions.ItemDiscountPromotionsSpec.Item discount amount off can created, edited, deleted(ItemDiscountPromotionsSpec.groovy:118)```

**Comment by sadsridh** [comment] 2019-03-11 18:57
@asolntsev , 
After further debugging the actual issue is because a collapsible that displays a list of buttons after its clicked does not seem to acknowledge the click() and so it never expands to display the '-editButton' in the above element and so it is flagged with displayed:false which is correct !

However, after watching the test during debug the below element 
![image](https://user-images.githubusercontent.com/32882327/54150028-eba16f80-440d-11e9-97cd-0da51179f487.png)
 does receive the click() but it does nothing. Manually this works fine in a the application.

**Comment by g-one** [comment] 2019-03-18 21:49
Even i'm facing the same issue with 5.2.2 version. 

<a class="automation-text" tabindex="-1" style="text-transform:uppercase;" data-bind="text: name, attr: { href: route, id: id }, css: { 'selectedStoreSubNav': window.location.href.contains(route) || (route.startsWith('/') &amp;&amp; window.location.href.contains(route.substring(1))) }" href="/test/test-only" id="7b1ddf0f-4189-e811-a959-000d3a981a2b">Test Only</a>

This is my element. Was able to get through this error with executeJavaScript but hoping we will have a solution for this.

**Comment by metalmolly** [comment] 2019-05-27 12:01
Looks like I'm facing the same issue since I updated from 5.1.0 to Selenide 5.2.0 as some test scripts fail when being run headless with Chrome. The following error message is displayed:
```
Element should have text '3.0.86' {.label-title-block-protocol-version td[0]}
Element: '<td displayed:false></td>'
```
Strange is that the capture screenshot doesn't show the complete browser window, as it seems to be 'truncated'. Only a part of the browser window is captured. The part that's missing has the element (.label-title-block-protocol-version td[0]).

Workaround for me:
Run the same test non-headless i.e. ``` Configuration.headless = false;``` or
revert to Selenide 5.1.0 (with the same ChromeDriver version) works fine in headless mode.

**Selenide Version:** 5.2.0, **Chrome Version:** 74.0.3729.131, **Browser Driver Version:** 74.0.3729.6
**Selenium Version:** 3.141.59, **OS Version:** Windows 10 Version 1803 (17134.765)

**Comment by BorisOsipov** [comment] 2019-05-27 12:03
@metalmolly it seems chromedriver\chrome issue, not selenide, isn't it?

**Comment by metalmolly** [comment] 2019-05-27 12:51
> @metalmolly it seems chromedriver\chrome issue, not selenide, isn't it?

@BorisOsipov but for me that doesn't explain why headless works using the same driver version with 5.1.0?

**Comment by sadsridh** [comment] 2019-05-28 18:21
I see the issue with Selenide 5.2.2 with the below config :
Selenide Version: 5.2.2, Chrome Version: 74.0.3729.131, Browser Driver Version: 2.46
Selenium Version: 3.141.59, OS Version: Windows 10 

@asolntsev  This bug fix is one of the main reason we are upgrading to the latest version...

**Comment by asolntsev** [comment] 2019-05-28 19:27
> Even i'm facing the same issue with 5.2.2 version.

@g-one Can you specify what issue exactly are you facing? I tried to click an element with HTML that you provided - and it worked. Also in headless mode. 

Probably you could create a new github issue with html and java code (so I could reproduce the problem)?

**Comment by asolntsev** [comment] 2019-05-28 19:29
@sadsridh Sorry, I didn't understand which issue do you have in this setup? 
Why are you using chromedriver 2.46? I believe Chrome 74 requires chromedriver 74 (not 2.46).
If your problem is still valid, please create a separate github issue with html and java code (so I could reproduce the problem).

**Closed by asolntsev** 2019-05-28 19:29 UTC
Labels: has pr

**Comment by Doktor-Avalanche** [comment] 2019-12-23 09:28
Hi, I'm facing the same problem I think.
This is a snippet of the html code

`<tbody><tr><td align="left" width="15px" style="vertical-align: top;"><div class="gwt-HTML x-link-previous-image" aria-hidden="true" style="display: none;"></div></td><td align="center" style="vertical-align: middle;"><div class="gwt-HTML primion-label gwt-Label monthAndYearLabel">Januari 2020</div></td><td align="right" width="15px" style="vertical-align: middle;" class="xh-highlight"><div class="gwt-HTML x-link-next-image" aria-hidden="false" style=""></div></td></tr></tbody>`


Trace :
Element should be visible {By.xpath: //div[contains(@class,'x-link-next-image')]}
Element: '<div aria-hidden="true" class="gwt-HTML x-link-next-image" displayed:false></div>'

I try to click on the right arrow in the calendar.

![1577092610137 0](https://user-images.githubusercontent.com/11409404/71349248-db0e5000-256e-11ea-83e1-fb1da2b8b5b3.png)
