### ISSUE TITLE
When running tests locally with Selenide versions above 14.2 web browser processes are left opened consuming 100% CPU

### ISSUE THREAD

**Issue by eternal-fail** [selenide/selenide#1398] opened 2021-02-10 01:52 UTC
## The problem
When running tests locally with Selenide version above 14.2 web browser processes are not closed after tests resulting in 100% CPU usage
![orphaned_chrome_100p_usage](https://user-images.githubusercontent.com/78832106/107452825-37a14580-6b4a-11eb-87bf-56503de21495.png)

## Tell us about your environment
* **Selenide Version**: > 14.2
* **Chrome\Firefox\IE Version**: Chrome (haven't tested others)
* **Browser Driver Version**: 88.0.4324.96
* **Selenium Version**: 3.141.59
* **OS Version**: Win 10

## Code To Reproduce Issue [ Good To Have ]
@BeforeEach
    void setUp() { Selenide.open(url); }

@AfterEach
    void cleanUp() {  Selenide.closeWebDriver(); }

**Comment by asolntsev** [comment] 2021-02-14 10:18
@eternal-fail Sorry, I cannot reproduce the problem. 
I am trying the following code, but all browsers get closed: https://gist.github.com/asolntsev/11d484c103b5c1bf9c0b4941ecbdd449

**Comment by eternal-fail** [comment] 2021-02-15 02:41
@asolntsev thank you for looking into it. I should have written in the description that I am using JUnit5 with parallel execution enabled. I modified your example to match mentioned criteria and was able to reproduce the issue, although it is random and I had to rerun tests several times until I got some hanging chrome.exe processes. It looks like the more tests there are, the biggest chance to run into the issue.
https://github.com/eternal-fail/TestHungProcessess18

**Comment by asolntsev** [comment] 2021-02-15 06:05
Thank you, I will investigate it.

**Comment by matraa** [comment] 2021-02-17 15:54
What is version 14.2? Typo?
Anyway, I have a similar problem since version 5.18.1 of Selenide using chrome/driver 88, Windows 10 and TestNG 7.3.0 running parallell tests. It seems as if Chrome processes are never closed, so the last tests run slowest. Processes remains even after the suite has finished executing, meaning the next run is slow already from start and so on. Eventually system becomes unusable and must be restarted or processes manually removed.

**Comment by BorisOsipov** [comment] 2021-02-17 16:13
>it is random and I had to rerun tests several times until I got some hanging chrome.exe processes. It looks like the more tests there are, the biggest chance to run into the issue.
eternal-fail/TestHungProcessess18

I've ran your tests 10 times and haven found any hanged chrome processes. Change `junit.jupiter.execution.parallel.config.fixed.parallelism` to 10 and repeated experiment and again there were no 
chrome processes.

It seems not selenide issue but bug in chromedriver.

Chromedriver - 88.0.4324.96
Chrome - 88.0.4324.182
Win 10 BuildNumber 19042

**Comment by asolntsev** [comment] 2021-02-17 20:02
@eternal-fail I still cannot reproduce the problem. 

NB! Why don't you try the latest version of Selenide? Your problem might be already fixed in 5.18.1

Closing the issue. Feel free to reopen if we get new information how to reproduce the problem.

**Comment by eternal-fail** [comment] 2021-02-18 00:42
It looks like chrome option "--no-sandbox" is causing the issue for me. It was added in 5.15.00 so exactly when my problems started and when I created webdriver by hand the issue is gone. Is there a clean way to disable that switch?

**Comment by asolntsev** [comment] 2021-02-20 21:36
@eternal-fail Strange: adding option `--no-sandbox` should make Chrome more stable. At least many users complained that they cannot run chrome inside of a container without `--no-sandbox` option. Are you really sure this option causes the problem, and not anything else?

To remove this option, you need to override `com.codeborne.selenide.webdriver.ChromeDriverFactory`. 
See for example https://github.com/selenide/selenide/blob/master/statics/src/test/java/integration/ChromeProfileByFactoryTest.java

**Comment by eternal-fail** [comment] 2021-02-22 00:18
@asolntsev  yes, I am sure. I tested with and without "--no-sandbox". It is some old chromedriver bug that was never resolved. It was reported here:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2311

It would be good to have it optional, to avoid creating custom drivers just to disable one switch.

**Comment by asolntsev** [comment] 2021-03-13 19:35
@eternal-fail Thank you for sharing the information! Now we know that `--no-sandbox` option can cause Chrome hanging on Windows.

So what can we do? 
I guess it's probably a bad idea to remove `--no-sandbox` from default parameters in Selenide because many people asked for it, and (if I am not mistaken) Chrome cannot run in Docker without this option. 

For know, it seems that you need to override Selenide default chrome options by overriding `ChromeDriverFactory` or `WebdriverProvider`.

**Closed by asolntsev** 2021-03-13 19:35 UTC
Labels: cannot preproduce, help wanted

**Comment by matraa** [comment] 2021-03-15 07:59
Is there an example somewhere on how to override the Selenide default Chrome options?
Usually they work just fine so it would be nice to keep them as is without repeating that source and just tweak a few of them like `--no-sandbox` or in my case the browser language for some tests. The examples I've seen for language changes it "globally" and affects all tests in the suite.

**Comment by asolntsev** [comment] 2021-03-17 15:48
@matraa Sure. It's quite easy:

1. Set a `browser` setting:
```
 Configuration.browser = MyFactory.class.getName();
```

2. Create a subclass of `ChromeDriverFactory`:
```
private static class MyFactory extends ChromeDriverFactory {
   @Override
    protected List<String> createChromeArguments(Config config, Browser browser) {
      return asList("--proxy-bypass-list=<-loopback>"); // no "--no-sandbox" here
    }
}
```

See working example in Selenide own tests: https://github.com/selenide/selenide/blob/master/statics/src/test/java/integration/ChromeProfileByFactoryTest.java

**Comment by SerjPo** [comment] 2022-02-06 13:13
Reproduced as easy as following:
Env: VMware VM: Fresh Win7 x64 with 2CPU 4GB RAM, IntelliJ IDEA 2021.3.2, JDK 17.0.2, Chrome 'Version 98.0.4758.80 (Official Build) (64-bit)'

pom.xml:
```
    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>6.2.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.35</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```
Test (taken from https://ru.selenide.org/quick-start.html):
```
    @Test
    public void userCanLoginByUsername() {
        open("/login");
        $(By.name("user.name")).setValue("johny");
        $("#submit").click();
        $(".loading_progress").should(disappear); // Waits until element disappears
        $("#username").shouldHave(text("Hello, Johny!")); // Waits until element gets text
    }
```
Once test finished the Chrome window get closes but Chrome process remains active in TaskManager and consume both CPU (25%) and memory as well. More over Chrome memory footprint get increased over time slowly up to the maximum RAM available and more, what leads to the page file get increased as well.

Whereas the following test works very well and doesn't have such problem:
```
    @Test
    public void emptyTest() {
        open();
    }
```

**Comment by asolntsev** [comment] 2022-02-07 05:16
@SerjPo thank you for sharing the code! Did you try to remove `--ni-sandbox` option as described in https://github.com/selenide/selenide/issues/1398#issuecomment-801192903 ?

**Comment by SerjPo** [comment] 2022-02-07 12:04
@asolntsev thank you for the suggestion. Tried to remove "--no-sandbox" option as you suggested and yep - issue is not reproduced any more! 10 times out of 10 the Chrome process get closed properly.
```
    @Test
    public void userCanLoginByUsername() {
        Configuration.browser = MyFactory.class.getName();
        open("/login");
    }

    private static class MyFactory extends ChromeDriverFactory {
        @Override
        protected List<String> createChromeArguments(Config config, Browser browser) {
            return asList("--proxy-bypass-list=<-loopback>"); // no "--no-sandbox" here
        }
    }
```
