### ISSUE TITLE
Add support for dynamic locators in page objects with parameterized to @FindBy annotations , like @FindBy(css = "div.btn i[title='{}']")

### ISSUE THREAD

**Issue by softommy** [selenide/selenide#1386] opened 2021-01-26 13:05 UTC
@FindBy(css = "div.btn i[title='{}']")
SelenideElement btnElement;

btnElement.with('ButtonX').click(); // `<div class="btn"><i title="ButtonX"/></div>`
btnElement.with('ButtonY').click(); //`<div class="btn"><i title="ButtonY"/></div>`

Add with methods in SelenideElement
SelenideElement.with(Object ...args)

**Comment by asolntsev** [comment] 2021-01-26 21:31
Hi @softommy . 
Thank you for registering the feature request. It's a duplicate of https://github.com/selenide/selenide/issues/1050, though. 

@softommy What do you think about suggestion in https://github.com/selenide/selenide/issues/1050#issuecomment-581789269 ?

**Closed by asolntsev** 2021-01-26 21:31 UTC
Labels: duplicate

**Comment by softommy** [comment] 2021-01-27 02:36
now i do like this with selenium api

```
#PageObject
@FindBy(xpath = "//div[starts-with(@class,'xxx-')]//label[text()='{0}']")
List<WebElement> labels;
@FindBy(xpath = "//div[starts-with(@class,'xxx-')]//label[text()='{0}']")
List<WebElement> firstLabel;
public void test(){
int xTextLblsize = elementsWithArgs(labels, 'XTEXT').size();
WebElement yTextLbl=proxyElementWithArg(firstLabel, 'YTEXT');
yTextLbl.click
}
# BaseClass
# For List 

protected List<WebElement> elementsWithArgs(List<WebElement> elements, Object... args) {
    this.proxyElementListWithArgs(elements, args);
    return elements;
}
private void proxyElementListWithArgs(List<WebElement> elements, Object... args) {
		if (args == null || args.length == 0) {
			return;
		}
		if (Proxy.isProxyClass(elements.getClass())) {
			LocatingElementListHandler handler = (LocatingElementListHandler) Proxy.getInvocationHandler(elements);
			try {
				Field locatorField = LocatingElementListHandler.class.getDeclaredField("locator");
				locatorField.setAccessible(true);
				DefaultElementLocator locator = (DefaultElementLocator) locatorField.get(handler);
				Field byFeild = DefaultElementLocator.class.getDeclaredField("by");
				byFeild.setAccessible(true);
				By by = (By) byFeild.get(locator);
				by = this.parameter(by, args);
				byFeild.set(locator, by);
			} catch (IllegalAccessException e) {
			} catch (NoSuchFieldException e) {
			}
		}
	}

	private void proxyElementWithArg(WebElement element, Object... args) {
		if (args == null || args.length == 0) {
			return;
		}
		if (Proxy.isProxyClass(element.getClass())) {
			LocatingElementHandler handler = (LocatingElementHandler) Proxy.getInvocationHandler(element);
			try {
				Field locatorField = LocatingElementHandler.class.getDeclaredField("locator");
				locatorField.setAccessible(true);
				DefaultElementLocator locator = (DefaultElementLocator) locatorField.get(handler);
				Field byFeild = DefaultElementLocator.class.getDeclaredField("by");
				byFeild.setAccessible(true);
				By by = (By) byFeild.get(locator);
				by = this.parameter(by, args);
				byFeild.set(locator, by);
			} catch (IllegalAccessException e) {
			} catch (NoSuchFieldException e) {
			}
		}
	}

	private By parameter(By by, Object... args) {
		String byDesc = by.toString();
		if (byDesc.indexOf(":") == -1) {
			return by;
		}
		String using = byDesc.substring(byDesc.indexOf(":") + 2);
		using = MessageFormat.format(using.replace("'", "''"), args);
		if (byDesc.startsWith("By.id")) {
			return By.id(using);
		} else if (byDesc.startsWith("By.name")) {
			return By.name(using);
		} else if (byDesc.startsWith("By.className")) {
			return By.className(using);
		} else if (byDesc.startsWith("By.cssSelector")) {
			return By.cssSelector(using);
		} else if (byDesc.startsWith("By.xpath")) {
			return By.xpath(using);
		} else if (byDesc.startsWith("By.tagName")) {
			return By.tagName(using);
		} else if (byDesc.startsWith("By.linkText")) {
			return By.linkText(using);
		} else if (byDesc.startsWith("By.partialLinkText")) {
			return By.partialLinkText(using);
		} else {
			return by;
		}
	}
```

**Comment by softommy** [comment] 2021-01-27 02:38
> Hi @softommy .
> Thank you for registering the feature request. It's a duplicate of #1050, though.
> 
> @softommy What do you think about suggestion in [#1050 (comment)](https://github.com/selenide/selenide/issues/1050#issuecomment-581789269) ?

now i do like this with selenium api
```
#PageObject
@FindBy(xpath = "//div[starts-with(@class,'xxx-')]//label[text()='{0}']")
List<WebElement> labels;
@FindBy(xpath = "//div[starts-with(@class,'xxx-')]//label[text()='{0}']")
List<WebElement> firstLabel;
public void test(){
int xTextLblsize = elementsWithArgs(labels, 'XTEXT').size();
WebElement yTextLbl=proxyElementWithArg(firstLabel, 'YTEXT');
yTextLbl.click
}
# BaseClass
# For List 

protected List<WebElement> elementsWithArgs(List<WebElement> elements, Object... args) {
    this.proxyElementListWithArgs(elements, args);
    return elements;
}
private void proxyElementListWithArgs(List<WebElement> elements, Object... args) {
		if (args == null || args.length == 0) {
			return;
		}
		if (Proxy.isProxyClass(elements.getClass())) {
			LocatingElementListHandler handler = (LocatingElementListHandler) Proxy.getInvocationHandler(elements);
			try {
				Field locatorField = LocatingElementListHandler.class.getDeclaredField("locator");
				locatorField.setAccessible(true);
				DefaultElementLocator locator = (DefaultElementLocator) locatorField.get(handler);
				Field byFeild = DefaultElementLocator.class.getDeclaredField("by");
				byFeild.setAccessible(true);
				By by = (By) byFeild.get(locator);
				by = this.parameter(by, args);
				byFeild.set(locator, by);
			} catch (IllegalAccessException e) {
			} catch (NoSuchFieldException e) {
			}
		}
	}

	private void proxyElementWithArg(WebElement element, Object... args) {
		if (args == null || args.length == 0) {
			return;
		}
		if (Proxy.isProxyClass(element.getClass())) {
			LocatingElementHandler handler = (LocatingElementHandler) Proxy.getInvocationHandler(element);
			try {
				Field locatorField = LocatingElementHandler.class.getDeclaredField("locator");
				locatorField.setAccessible(true);
				DefaultElementLocator locator = (DefaultElementLocator) locatorField.get(handler);
				Field byFeild = DefaultElementLocator.class.getDeclaredField("by");
				byFeild.setAccessible(true);
				By by = (By) byFeild.get(locator);
				by = this.parameter(by, args);
				byFeild.set(locator, by);
			} catch (IllegalAccessException e) {
			} catch (NoSuchFieldException e) {
			}
		}
	}

	private By parameter(By by, Object... args) {
		String byDesc = by.toString();
		if (byDesc.indexOf(":") == -1) {
			return by;
		}
		String using = byDesc.substring(byDesc.indexOf(":") + 2);
		using = MessageFormat.format(using.replace("'", "''"), args);
		if (byDesc.startsWith("By.id")) {
			return By.id(using);
		} else if (byDesc.startsWith("By.name")) {
			return By.name(using);
		} else if (byDesc.startsWith("By.className")) {
			return By.className(using);
		} else if (byDesc.startsWith("By.cssSelector")) {
			return By.cssSelector(using);
		} else if (byDesc.startsWith("By.xpath")) {
			return By.xpath(using);
		} else if (byDesc.startsWith("By.tagName")) {
			return By.tagName(using);
		} else if (byDesc.startsWith("By.linkText")) {
			return By.linkText(using);
		} else if (byDesc.startsWith("By.partialLinkText")) {
			return By.partialLinkText(using);
		} else {
			return by;
		}
	}
```

**Comment by asolntsev** [comment] 2021-01-27 11:29
@softommy Wow, how complex is this code! It's just incredible... 

@softommy Still, what do you think about suggestion in [#1050](https://github.com/selenide/selenide/issues/1050#issuecomment-581789269) ? It seems to be much simpler.

**Comment by softommy** [comment] 2021-02-25 09:24
> @softommy Wow, how complex is this code! It's just incredible...
> 
> @softommy Still, what do you think about suggestion in [#1050](https://github.com/selenide/selenide/issues/1050#issuecomment-581789269) ? It seems to be much simpler.

There is an urgent need to support the use of placeholders in PageObject feild declarations and dynamic parameterization at runtime. When the product needs to be internationalized, the locate of actual elements in different languages can be conveyed, example:
@findby(css = "span[title='{}']")
SelenideElement element;

element.withArgs

> > Hi @softommy .
> > Thank you for registering the feature request. It's a duplicate of #1050, though.
> > @softommy What do you think about suggestion in [#1050 (comment)](https://github.com/selenide/selenide/issues/1050#issuecomment-581789269) ?
> 
> now i do like this with selenium api
> 
> ```
> #PageObject Class
>     @FindBy(xpath = "//div[starts-with(@class,'xxx-')]//label[text()='{0}']")
>     List<WebElement> labels;
>     @FindBy(xpath = "//div[starts-with(@class,'xxx-')]//label[text()='{0}']")
>     WebElement firstLabel;
> 
>     public void test(){
>         int xTextLblsize = proxyElementListWithArgs(labels, 'XTEXT').size();
>         WebElement yTextLbl=proxyElementWithArg(firstLabel, 'YTEXT');
>         yTextLbl.click
>     }
> # BaseClass
> # For List 
> 
>     private void proxyElementListWithArgs(List<WebElement> elements, Object... args) {
>         if (args == null || args.length == 0) {
>             return;
>         }
>         if (Proxy.isProxyClass(elements.getClass())) {
>             LocatingElementListHandler handler = (LocatingElementListHandler) Proxy.getInvocationHandler(elements);
>             try {
>                 Field locatorField = LocatingElementListHandler.class.getDeclaredField("locator");
>                 locatorField.setAccessible(true);
>                 DefaultElementLocator locator = (DefaultElementLocator) locatorField.get(handler);
>                 Field byFeild = DefaultElementLocator.class.getDeclaredField("by");
>                 byFeild.setAccessible(true);
>                 By by = (By) byFeild.get(locator);
>                 by = this.parameter(by, args);
>                 byFeild.set(locator, by);
>             } catch (IllegalAccessException e) {
>             } catch (NoSuchFieldException e) {
>             }
>         }
>     }
> 
>     private void proxyElementWithArg(WebElement element, Object... args) {
>         if (args == null || args.length == 0) {
>             return;
>         }
>         if (Proxy.isProxyClass(element.getClass())) {
>             LocatingElementHandler handler = (LocatingElementHandler) Proxy.getInvocationHandler(element);
>             try {
>                 Field locatorField = LocatingElementHandler.class.getDeclaredField("locator");
>                 locatorField.setAccessible(true);
>                 DefaultElementLocator locator = (DefaultElementLocator) locatorField.get(handler);
>                 Field byFeild = DefaultElementLocator.class.getDeclaredField("by");
>                 byFeild.setAccessible(true);
>                 By by = (By) byFeild.get(locator);
>                 by = this.parameter(by, args);
>                 byFeild.set(locator, by);
>             } catch (IllegalAccessException e) {
>             } catch (NoSuchFieldException e) {
>             }
>         }
>     }
> 
>     private By parameter(By by, Object... args) {
>         String byDesc = by.toString();
>         if (byDesc.indexOf(":") == -1) {
>             return by;
>         }
>         String using = byDesc.substring(byDesc.indexOf(":") + 2);
>         using = MessageFormat.format(using.replace("'", "''"), args);
>         if (byDesc.startsWith("By.id")) {
>             return By.id(using);
>         } else if (byDesc.startsWith("By.name")) {
>             return By.name(using);
>         } else if (byDesc.startsWith("By.className")) {
>             return By.className(using);
>         } else if (byDesc.startsWith("By.cssSelector")) {
>             return By.cssSelector(using);
>         } else if (byDesc.startsWith("By.xpath")) {
>             return By.xpath(using);
>         } else if (byDesc.startsWith("By.tagName")) {
>             return By.tagName(using);
>         } else if (byDesc.startsWith("By.linkText")) {
>             return By.linkText(using);
>         } else if (byDesc.startsWith("By.partialLinkText")) {
>             return By.partialLinkText(using);
>         } else {
>             return by;
>         }
>     }
> ```

There is an urgent need to support the use of placeholders in PageObject feild declarations and dynamic parameterization at runtime. When the product needs to be internationalized, the locate of actual elements in different languages can be conveyed, example

@findby(css = "span[title='{}']")
SelenideElement spanElement;

# add withArgs command in SelenideElement
spanElement.withArgs("English").click(); // Locale en
spanElement.withArgs("中文").click(); // Locale zh_CN

**Comment by sleepstream** [comment] 2024-09-09 11:06
@asolntsev 
It's closed without resolution?
Or it's released?

I need it very much to work with fragments (ElementsContainer) 
For example:
![изображение](https://github.com/user-attachments/assets/daba6887-9e47-40b2-bc8b-36f0f6a80e00)

**Comment by mikita-yafimuk** [comment] 2024-12-09 12:47
@asolntsev closed with resolution "it seems we can close it because people didn't like the idea.". But across all comment in #1050 people say that it would be great to add such a feature. Why did you decide that people don't like this idea? That would be really awesome to support dynamic locators for locating elements in different languages (internationalized products and etc.)
