### ISSUE TITLE
java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property

### ISSUE THREAD

**Issue by nimbus0** [selenide/selenide#2464] opened 2023-09-07 05:01 UTC
Hello There,

So after the chrome update for chrome for testing, in my test automation framework I have update the following

1. Selenide versions fron6.5.0 to 6.17.2 - for selenium manager
2. I use docker compose  where the image is updated to selenium/standalone-chrome:116.0-chromedriver-116.0-20230904

## The problem
java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from https://chromedriver.storage.googleapis.com/index.html

What am I missing to update here, the path is never changed, do I need to edit or add the path somewhere? Please suggest.  I am using Kotlin and gradle build tool

**Comment by asolntsev** [comment] 2023-09-07 06:40
@nimbus0 No, you don't need to set path to driver. You also don't need to download chromedriver. 
Selenide 6.17.2 downloads chromedriver automatically.

I assume you have some old version of chromedriver in PATH, or some old version of Selenium/Selenide/WebdriverManager in classpath. Fast check:
1. run `chromedriver -version` in terminal
2. run `gradle dependencies` and check versions

**Comment by nimbus0** [comment] 2023-09-07 13:55
Hi Thank you for the response,

I have checked the terminal there is no driver versions and also the dependencies passed.

When I run gradle test , I get the below error
![image](https://github.com/selenide/selenide/assets/18535355/8e6fc021-6018-4e05-818f-61ff641bcc85)


java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wi
ki/ChromeDriver. The latest version can be downloaded from https://chromedriver.storage.googleapis.com/index.html
        at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:311)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:135)
        at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:38)
        at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:231)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:437)
        at com.codeborne.selenide.webdriver.AbstractDriverFactory.withLog(AbstractDriverFactory.java:52)
        at com.codeborne.selenide.webdriver.ChromeDriverFactory.buildService(ChromeDriverFactory.java:40)
        at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:34)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:120)
        at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
        at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
        at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:113)
        at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:205)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createAndRegisterDriver(WebDriverThreadLocalContainer.java:190)
        at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:152)
        at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
        at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
        at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:222)
        at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:71)
        at com.codeborne.selenide.logevents.SelenideLogger.lambda$run$0(SelenideLogger.java:105)
        at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
        at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:104)
        at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:69)
        at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
        at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
        at com.codeborne.selenide.Selenide.open(Selenide.java:53)

**Comment by asolntsev** [comment] 2023-09-07 16:08
@nimbus0 What about the second item?
> run gradle dependencies and check versions

**Comment by mike35490** [comment] 2023-09-08 05:25
Hi,
I have a similar issue.
After some research I think this might be related to the newest versions of Chrome (115 and 116).

The webdrivers for them are not available at https://chromedriver.storage.googleapis.com/index.html and I think that this is the cause of the issue and this is why Selenide (webDriverManager) can't match and download correct webdrivers for newest Chrome versions and asks for providing them.

On the https://chromedriver.chromium.org/downloads page, at the top there is a statement: 

> "If you are using Chrome version 115 or newer, please consult [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading."

When I manually downloaded the webdriver for version 116 and set the System parameter
`System.setProperty("webdriver.chrome.driver", "PATH_TO_WEBDRIVER\chromedriver.exe");`

After that - Selenide was able to open the browser.

**Comment by mike35490** [comment] 2023-09-08 05:26
Hi,
I have a similar issue.
After some research I think this might be related to the newest versions of Chrome (115 and 116).

The webdrivers for them are not available at https://chromedriver.storage.googleapis.com/index.html and I think that this is the cause of the issue and this is why Selenide (webDriverManager) can't match and download correct webdrivers for newest Chrome versions and asks for providing them.

On the https://chromedriver.chromium.org/downloads page, at the top there is a statement: 

> "If you are using Chrome version 115 or newer, please consult [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading."

When I manually downloaded the webdriver for version 116 and set the System parameter
`System.setProperty("webdriver.chrome.driver", "PATH_TO_WEBDRIVER\chromedriver.exe");`

After that - Selenide was able to open the browser.

**Comment by asolntsev** [comment] 2023-09-08 05:38
@mike35490 No-no, you don't really need this.

1. Yes, you found the correct information: Chrome 115+ has changed downloads location.
2. BUT latest Selenide/Selenium/WebDriverManager can download chromedriver from the right location. 

So you don't need to manually download or install any drivers.

**Comment by mike35490** [comment] 2023-09-08 06:01
Ok, so leaving some info about My case - maybe this will help in further investigation of the issue:

Selenide version 6.18.0 

Stacktrace:

`2023-09-08 07:51:42.145 [main] [INFO ] c.c.s.i.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
2023-09-08 07:51:42.168 [main] [INFO ] c.c.s.i.FileHelper - Creating folder: C:\dev\npm-automatization\target\downloads\1694152302165_5988_1

java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads

	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:311)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:135)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:437)
	at com.codeborne.selenide.webdriver.AbstractDriverFactory.withLog(AbstractDriverFactory.java:52)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.buildService(ChromeDriverFactory.java:40)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:34)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:120)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:67)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
	at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
	at com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:113)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:205)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createAndRegisterDriver(WebDriverThreadLocalContainer.java:190)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:152)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:223)
	at com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:71)
	at com.codeborne.selenide.logevents.SelenideLogger.lambda$run$0(SelenideLogger.java:105)
	at com.codeborne.selenide.logevents.SelenideLogger.wrap(SelenideLogger.java:133)
	at com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:104)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:69)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:102)
	at com.codeborne.selenide.Selenide.open(Selenide.java:53)
	at pl.nowaera.qa.testcases.santillanago.SgoBaseTest.openLoginPage(SgoBaseTest.java:173)
	at pl.nowaera.qa.testcases.santillanago.SgoBaseTest.setUp(SgoBaseTest.java:168)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)`

**Comment by asolntsev** [comment] 2023-09-10 08:50
@mike35490 No, it's not enough. We need to know more:

> run `gradle dependencies` and check versions of Selenium, Selenide, WebDriverManager etc.

**Comment by asolntsev** [comment] 2023-09-10 08:51
Anyway, I am closing the issue because it's clearly not a Selenide problem.

**Closed by asolntsev** 2023-09-10 08:51 UTC
Labels: cannot reproduce, question, dependencies

**Comment by nimbus0** [comment] 2023-09-12 13:29
Ran all dependencies check , gradle upgrade for 8 is throwing error so have to stick to 7.4 same is for every dependency...
Kotlin is 1.7.20 version 1.8.0 is throwing error with plugin.

Upgraded spring boot to 3 but it's giving different error.

![image](https://github.com/selenide/selenide/assets/18535355/0b25b435-21d8-49bb-b4da-ee0fb79e2e4a)

I am stuck.

**Comment by nimbus0** [comment] 2023-09-12 13:30
I have no where any selenium dependency except selenide. Others are docker, springboot, junit, kotlin, java 11

**Comment by BorisOsipov** [comment] 2023-09-12 13:32
@nimbus0 

It will help https://stackoverflow.com/questions/70881256/selenium-4-1-and-spring-boot-web-driver-version-issue

**Comment by nimbus0** [comment] 2023-09-13 06:44
@BorisOsipov 
That worked, thank you so much!

**Comment by mike35490** [comment] 2023-09-14 10:12
> @nimbus0
> 
> It will help https://stackoverflow.com/questions/70881256/selenium-4-1-and-spring-boot-web-driver-version-issue

Yes, that works also for me - just placed property in my pom.xml `<selenium.version>4.12.1</selenium.version>` . 

I didn't expect the Selenium version coming from Spring-boot parent instead of Selenide 😅

Thanks for Your help!
