### ISSUE TITLE
Selenide click doesn't work while Selenium click does

### ISSUE THREAD

**Issue by SergiiTrybushnyi** [selenide/selenide#1475] opened 2021-05-24 12:30 UTC
During migration of our test from Serenity to Selenide I've come across weird behaviour of SelenideElement.click() method. 

I have a confirmation popup, which has 2 buttons: "Remove" and "Cancel"  it's just for example. I have issues with all the buttons and some fields on this popup. 

If I try 
`$(element).shouldBe(visible).click() `
I receive error 
```
Element not found {.message-confirmation-container .modal-header/By.xpath: .//button[.='Remove']}
Expected: visible or transparent: visible or have css value opacity=0
```

If I do it with 
`getDriver().findElement(By.xpath("//button[.='Remove']")).click();`
I have no issues and element is clicked.

The same with 
`$(element).toWebElement().click()` - works fine

Selenide 5.20.4
Chrome 90.0.4430.24

The button in the html looks like: 
```<div _ngcontent-c11="" aria-labelledby="dialog-sizes-name1" bsmodal="" class="modal fade message-confirmation-container in" role="dialog" tabindex="-1" aria-hidden="false" aria-modal="true" style="display: block;">
<div _ngcontent-c11="" class="modal-dialog modal-sm">
<div _ngcontent-c11="" class="modal-content">
<div _ngcontent-c11="" class="modal-header">
<h4 _ngcontent-c11="">Are you sure you want to remove all selected promo codes?</h4></div>
<div _ngcontent-c11="" class="modal-body table-container">
<button _ngcontent-c11="" class="btn btn-primary" type="button">Remove</button>
<button _ngcontent-c11="" class="btn btn-default" type="button">Cancel</button>
</div></div></div></div>
```

Maybe it's connected somehow to our DOM, because at the time we open the page all the buttons exist on the page, but they become truly visible when appropriate button is clicked. And for some reason WebElement.click() can click on them, while SelenideElement.click() cannot. 

Thank you

**Comment by BorisOsipov** [comment] 2021-05-24 12:35
@SergiiTrybushnyi could you share full error stacktrace via pastebin.com\gist.github.com?

**Comment by SergiiTrybushnyi** [comment] 2021-05-24 12:40
> @SergiiTrybushnyi could you share full error stacktrace via pastebin.com\gist.github.com?

https://pastebin.com/MMjZ8J97

What I noticed else, that this is reproduced only when tests are run in background. If I launch test > change focus to IDE, test gets failed. If I launch test and watch the browser > test passes successfully.

**Comment by BorisOsipov** [comment] 2021-05-24 12:46
@SergiiTrybushnyi stacktrace is cropped

**Comment by SergiiTrybushnyi** [comment] 2021-05-24 13:01
> @SergiiTrybushnyi stacktrace is cropped

here is the full paste
https://pastebin.com/XUkhy4NV

**Comment by anilreddy** [comment] 2021-05-24 13:59
@SergiiTrybushnyi as per the stack trace it is not visible can you do like this:

```java
$x(".//button[.='Remove']").shouldBe(visible).click();
```

**Comment by SergiiTrybushnyi** [comment] 2021-05-24 14:30
> @SergiiTrybushnyi as per the stack trace it is not visible can you do like this:
> 
> ```java
> $x(".//button[.='Remove']").shouldBe(visible).click();
> ```

```
Element should be visible {By.xpath: //button[.='Remove']}
Element: '<button _ngcontent-c11 class="btn btn-primary" type="button" value displayed:false></button>'
Actual value: visible:false
Screenshot: ...
Page source: ...
Timeout: 20 s.
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:121)
	at com.codeborne.selenide.commands.Should.execute(Should.java:30)
	at com.codeborne.selenide.commands.Should.execute(Should.java:14)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:155)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:133)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:85)
	at com.sun.proxy.$Proxy29.shouldBe(Unknown Source)
	at pages.project.PromoCodesPage.removePromoCode(PromoCodesPage.java:45)
	at steps.PromoCodeSteps.removePromoCode(PromoCodeSteps.java:46)
	at project.promoCodes.PromoCodesTest.testCanCreatePromoCodeAllUsersAutoGeneratedCode(PromoCodesTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
```

**Comment by anilreddy** [comment] 2021-05-24 15:41
@SergiiTrybushnyi can you check if the Remove button is single on the page or are there multiple

**Comment by SergiiTrybushnyi** [comment] 2021-05-24 15:52
> @SergiiTrybushnyi can you check if the Remove button is single on the page or are there multiple

Done this, only 1 button on the page

**Comment by asolntsev** [comment] 2021-05-24 22:49
@SergiiTrybushnyi The error message `Element should be visible {By.xpath: //button[.='Remove']}` clearly says that the **"Remove" button is not visible**, so the end user cannot click it. I think it's a correct behaviour of test if it fails to click an invisible button. Probably the confirmation popup is not yet visible at that moment?

You probably need to perform some other action to make this button visible. For example, open the confirmation popup.

**Comment by SergiiTrybushnyi** [comment] 2021-05-25 08:15
> @SergiiTrybushnyi The error message `Element should be visible {By.xpath: //button[.='Remove']}` clearly says that the **"Remove" button is not visible**, so the end user cannot click it. I think it's a correct behaviour of test if it fails to click an invisible button. Probably the confirmation popup is not yet visible at that moment?
> 
> You probably need to perform some other action to make this button visible. For example, open the confirmation popup.

Hi Andrei. Your words make sense, but not in this case.
Again
$(element).shouldBe(visible).click() - throws Should exception
getDriver().findElement(By.cssSelector(element)).click() - works fine

**Comment by anilreddy** [comment] 2021-05-25 15:12
@SergiiTrybushnyi  as per the info it is not an issue from selenide close this issue

**Comment by asolntsev** [comment] 2021-05-25 20:49
@SergiiTrybushnyi Can you share a fully working example so that we could reproduce the problem?
I am trying to run these 3 tests:

```java
  @Test
  void selenium() {
    getWebDriver().findElement(By.xpath("//button[.='Remove']")).click();
  }

  @Test
  void selenide() {
    $x("//button[.='Remove']").click();
  }

  @Test
  void selenide_workaround() {
    $x("//button[.='Remove']").toWebElement().click();
  }
```

against your html from comment https://github.com/selenide/selenide/issues/1475#issue-899616714 - and they all work.

When I add `style="display: none"` to the "Remove" button, all 3 tests start failing. 

By the moment I cannot reproduce the issue.

**Comment by SergiiTrybushnyi** [comment] 2021-05-28 09:08
> @SergiiTrybushnyi Can you share a fully working example so that we could reproduce the problem?
> I am trying to run these 3 tests:
> 
> ```java
>   @Test
>   void selenium() {
>     getWebDriver().findElement(By.xpath("//button[.='Remove']")).click();
>   }
> 
>   @Test
>   void selenide() {
>     $x("//button[.='Remove']").click();
>   }
> 
>   @Test
>   void selenide_workaround() {
>     $x("//button[.='Remove']").toWebElement().click();
>   }
> ```
> 
> against your html from comment [#1475 (comment)](https://github.com/selenide/selenide/issues/1475#issue-899616714) - and they all work.
> 
> When I add `style="display: none"` to the "Remove" button, all 3 tests start failing.
> 
> By the moment I cannot reproduce the issue.

Seems like issue is related to Xvfb somehow. I was still experiencing the issue, but after I resized window in Xvfb to 1920x1080 instead of 1024x768 which was set during quick-setup of Jenkins job, most "visibility" exceptions are gone.

**Comment by BorisOsipov** [comment] 2021-05-28 09:16
ok close then

**Closed by BorisOsipov** 2021-05-28 09:16 UTC
Labels: cannot preproduce, waiting-for-author
