### ISSUE TITLE
iterator, listIterator, spliterator and stream methods should return objects that don’t depend on ElementCollection

### ISSUE THREAD

**Issue by evpl** [selenide/selenide#1267] opened 2020-09-08 14:31 UTC
## The problem
I’ve read that’s in 4.12.3 `iterator` and `listIterator` methods are no longer updating `ElementCollection`. I think it’s a step in the right direction. However, in my opinion the new objects returned by collection should not be dependent on `ElementCollection` structure.

Getting element from the collection scenario:
```java
ElementCollection elementCollection = $$(...); // not empty
SelenideElement element = elementCollection.get(0);
Selenide.refresh(); // open the same page
String elementString = element.toString(); // element found
```
However, currently this behavior is not obvious:
```java
ElementCollection elementCollection = $$(...); // not empty
SelenideElement element = elementCollection.stream().collect(Collectors.toList()).get(0);
Selenide.refresh(); // open the same page
String elementString = element.toString(); // StaleElementReferenceException
```
It happens due to splitterator method is not overridden and it receives `ElementCollection`:
```java
default Spliterator<E> spliterator() {
	return Spliterators.spliterator(this, Spliterator.ORDERED);
}
```
And not overridden method stream uses this method:
```java
default Stream<E> stream() {
	return StreamSupport.stream(spliterator(), false);
}
```
To implement stream method without its dependence on collections I use independent elements creation method `toArray` by `ArrayList` constructor:
```java
Stream<SelenideElement> stream = new ArrayList<>(elementCollection).stream();
```
The same goes for iterator and listIterator methods.

## Solution
To override spliterator method by using elements which are independent of collection with `toArray` method. It also affects stream method.
```java
public Spliterator<E> spliterator() {
	return Spliterators.spliterator(this.toArray(), Spliterator.ORDERED);
}
```
Similar solutions (using independent `SelenideElements`) can be applied to methods iterator and listIterator.

**Comment by asolntsev** [comment] 2020-09-08 18:40
@evpl Can you specify what is the real problem? Is something broken?

In some sense, `StaleElementReferenceException` after putting the previous value to a variable and refreshing the page is totally reasonable behaviour...

P.S. Isn't it a duplicate of https://github.com/selenide/selenide/issues/797 ?

**Comment by evpl** [comment] 2020-09-13 16:21
This is not a duplicate of #797, but a similar problem.

It’s an example from the real project:
```
List<SomeObject> list = $$(...).stream()
	.map(element -> new SomeObject(element)) // SomeObject receive SelenideElement by constructor and save it
	.collect(Collectors.toList());
```
I get an `StaleElementReferenceException` when I try to execute actions by `SomeObject` (and inner `SelenideElement`).

I don't expect to see a `StaleElementReferenceException` at all when I use Selenide. I see two problems:

1. Using the `get(int index)` method, we get a `SelenideElement` that implicitly updates the collection from which it was taken. It means an unobvious relation between objects; side effect can lead to unexpected behavior in tests. Why can't we create a unique `SelenideElement` that doesn't depend on the collection? Current behavior is if the element is lost from the page, `SelenideElement` will reload the collection and the element will be found again or the element will display an `IndexOutOfBoundsException` (which differs from the standard exception shown by `SelenideElement`).
2. Using the `iterator` and receiving the element by the `next()` method after the element is lost, a `StaleElementReferenceException` will be shown in any case, since we are working with `WebElement` references. Again, why not just create an independent `SelenideElement`? The same goes for `listIterator` / `splitterator` / `stream`.

I believe that in both cases the user should receive independent `SelenideElements` without binding to `ElementCollection` or `WebElement`, and he can interact with it in any way that suits him. Simmilar to `$(By seleniumSelector, int index)` and `$(By seleniumSelector, int index)` methods.

I associate the inability to return independent `SelenidElement` with the ability to create `SelenidElement` and `ElementCollection` not only by the `String` selectors or Selenium `By` mechanism, but via `WebElement` wrapping as well. I have never felt the need to wrap a `WebElement` and I am sure that most users have the same feeling too. I understand that such functionality may be needed for a library that extends the use of `WebElement` but Selenide is a full-fledged framework. I also see that in the latest version 5.14.2 for `Selenide.$(...)` and `Selenide.$$(...)` methods that accept WebElements were marked `@Deprecated`. Therefore, after prohibiting the creation of `WebElements` wrappings, you will probably need to correct the behavior of the `ElementCollection`.

**Comment by asolntsev** [comment] 2020-09-13 21:01
@evpl Thank you for the explanation. I see that it's exactly #797 issue :)

> Again, why not just create an independent SelenideElement?
Yes, it's possible. And #797 suggests exactly that. The only problem is that it will make your test _slower_. In some cases, _much more slower_.

Probably we will do it, but can you explain why do you need such a code?
```
List<SomeObject> list = $$(...).stream().map(element -> new SomeObject(element)).collect(toList());
```

I don't see any benefit from it. 

The initial idea of collections in Selenide was to perform one-line checks like `$$(...).shouldHave(...)`.   
It was not intended to iterate them or convert to some object objects.   
I regret that `ElementsCollection` extends `List` :(

**Comment by asolntsev** [comment] 2020-09-21 18:48
@evpl ^^^ ping ^^^

**Comment by evpl** [comment] 2020-09-25 06:14
@asolntsev 
Sorry for late response, got a lot of work this week :)

Now I see similarity with #797. 
I don’t think we should care about UI tests productivity. If the “some cases, much slower” problem is caused by the change, maybe the tests themselves are the problem.

I use stream for creating page objects. Example:
```
public final class Block {
    private static final String ITEMS_CSS_SELECTOR = "[item]";
    private final SelenideElement block = $("[block]");
    private final SelenideElement tag = block.$("[tag]");

    public Block() {
    }

    public Block shouldBeVisible() {
        block.shouldBe(visible);
        return this;
    }

    public Block shouldHaveTag() {
        tag.shouldBe(visible).shouldHave(exactText("Tag"));
        return this;
    }

    public Block shouldHaveItemsCount(int count) {
        block.$$(ITEMS_CSS_SELECTOR).shouldHaveSize(count);
        return this;
    }

    public List<Item> items();

    public static final class Item {
        private final SelenideElement item;

        private Item(final SelenideElement item) {
            this.item = item;
        }

        public Item shouldBeVisible() {
            item.shouldBe(visible).shouldHave(matchText("Item #\\d+"));
            return this;
        }

        public Item shouldHaveNumber(int number) {
            item.shouldBe(visible).shouldHave(exactText("Item #" + number));
            return this;
        }
    }
}
```
```
final Block block = new Block();
block.shouldHaveItemsCount(5);
final List<Item> items = block.items();
items.get(0).shouldHaveNumber(1);
```

At first I used this implementation of the `List<Item> items()` method but after the 4.12.3 version it started to return `StaleElementException` when I update the page:
```
return block.$$("...")
	.stream()
	.map(element -> new Item(element))
	.collect(Collectors.toList());
```

Then I started to use this implementation, but there was a chance of `IndexOutOfBoundsException`:
```
return new ArrayList<>(block.$$("..."))
	.stream()
	.map(Item::new)
	.collect(Collectors.toList());
```

And now I use the 3rd option – storing locator outside of `ElementCollection`:
```
final String cssSelector = "...";
final int count = block.$$(cssSelector).size();
final List<Item> items = new ArrayList<>(count);
for (int idx = 0; idx < count; ++idx) {
	items.add(new Item($(cssSelector, idx)));
}
return items;
```

This option is not perfect. If I want to get only visible elements the amount of code increases and its readability suffers greatly:
```
final String cssSelector = "...";
final List<Item> items = new ArrayList<>();
for (int idx = 0; ; ++idx) {
	final SelenideElement element = $(cssSelector, idx);
	if(!element.exists()){
		break;
	}
	if(element.is(visible)) {
		items.add(new Item(element));
	}
}
return items;
```

I think it is possible to add new method to the `ElementCollection`: `List<SelenideElement> asIndependedElements()` which can be implemented as described in the option 3 – simple `ArrayList`. Therefore, `List` `iterator()` and other methods will work for me. The code would also look way better:
```
return $$("...").filter(visible)
	.asIndependedElements()
	.stream()
	.map(element -> new Item(element))
	.collect(Collectors.toList());
```

Regarding the correct implementation of `ElementCollection`, I thought about it many times but I can’t find the perfect way. Nevertheless, I learned a lot of new stuff because of committing the first issue :)

**Comment by asolntsev** [comment] 2020-11-23 22:44
Thank you for the explanation. 
I would close this ticker by the moment because we don't have concrete ideas anyway. We can resume the topic at any moment if someone gets fresh ideas.

**Closed by asolntsev** 2020-11-23 22:44 UTC
Labels: collections, waiting-for-author
