### ISSUE TITLE
PROXY downloads file to 2 locations.

### ISSUE THREAD

**Issue by MaciejGrymuza** [selenide/selenide#1025] opened 2019-12-04 13:55 UTC
Hi,
I have a problem when I use proxy download. 
The command element.download(); works, but it downloads file to the default folder (build/reports/tests/newFolderNumber). Unfortunately I have noticed that the file I wanted to download is also in system Downloads folder. It makes cleaning up after tests hard.

Env:
Selenide Version 5.5.1
Chrome:  78.0.3904.108 
Win 10

Configuration settings:
Configuration.proxyEnabled = true;
Configuration.fileDownload = PROXY;

**Comment by asolntsev** [comment] 2019-12-07 20:58
Hi @MaciejGrymuza 
Yes, in "proxy" mode method `$.download()` saves the file into 2 places. 
It allows the browser to download file to whatever location is by default, and saves a copy to "build/reports". 

**What are you suggesting?**

The problem is that configuration of "default download folder" for different browsers is different. 
We could try to set it up for Chrome, Firefox and probably some other popular webdrivers, but we cannot guarantee that for some other browser we wouldn't left the default directory...

**Comment by MaciejGrymuza** [comment] 2019-12-08 20:15
Hi @asolntsev !
Thank you very much for your response. In general - I'm very happy that you implemented Proxy download, it helps a lot with operating on files and it lets us to avoid setting up the configuration for browser behavior. 

The thing is that if we keep downloading files like we currently do, it will generate the risk of loosing big amount of memory in our drive. Let's imagine that in our tests we download big files (and of course we set the timeout for some longer time to be able to download it). If we download lots of files we have them stored in 2 places, which means that we will have to create some self-cleaning method to delete them from 2 locations(this raises the risk of complicating our code), or we will have to delete them manually. When we forget to do it, we will be loosing more and more memory - this can happen especially to inexperienced users.

1. If currently the responsibility for taking care of download directory is on the user's side, maybe it would be better just to leave the default directory and let the user to indicate only 1 location of our files to be deleted after tests? 

2. Or maybe it's a good idea to let user decide in Configuration class to keep only default location?

3. Or maybe it's a good idea to do it the way that you suggested - let's set it for main browsers like chrome, firefox etc. , and make it clear in the documentation that other browsers can store files in 2 locations? 

Sorry for giving 3 ideas, but I understand that the solution should be as universal as it's possible :)

**Comment by asolntsev** [comment] 2019-12-19 15:14
Hi @MaciejGrymuza.
Probably it's a good idea to add setting like `Configuration.downloadFolder` anyway. When downloading files with HTTPGET, people also want to download them to a custom location (instead of default `build/reports/tests`.

**Comment by asolntsev** [comment] 2020-01-08 21:05
E.g. here is describe how to customize download location for Chrome and Firefox: https://www.automatetheplanet.com/10-advanced-webdriver-tips-tricks-part-3/

**Comment by MaciejGrymuza** [comment] 2020-01-10 09:08
@asolntsev Thanks for the response. I suggested changing it cause it would give more control over downloading process to all of the users. Thanks for the link, it's useful also for general configuration of browsers.

**Comment by rosolko** [comment] 2020-01-27 18:43
Closed in #1041

**Closed by rosolko** 2020-01-27 18:43 UTC
Labels: feature, help wanted
