### ISSUE TITLE
Sizzle is not injected when switching into iframe

### ISSUE THREAD

**Issue by saboteurserg** [selenide/selenide#430] opened 2016-12-01 10:05 UTC
After switching to iframe and trying to use Sizzle i receive following error :

"WebDriverException: unknown error: Sizzle is not defined"

Seems like it's not injected to iframe

**Comment by BorisOsipov** [comment] 2016-12-01 14:02
Hi @saboteurserg 
Unfortunately, I have not reproduced the issue.

[Here ](https://github.com/BorisOsipov/selenide/commit/4e6b341697d0e6995ad5b0dbd212b2eaa69769a8) you can find example of test which I did.
Is it the same case?
Please give example code with issue and error log.

**Comment by saboteurserg** [comment] 2016-12-01 15:30
I am getting following stacktrace:

```
Element not found {[id='add-tile-btn']}
Expected: visible

Timeout: 4 s.
Caused by: WebDriverException: unknown error: Sizzle is not defined
	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:31)
	at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:82)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:59)
	at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsVisible(WebElementSource.java:72)
	at com.codeborne.selenide.commands.Click.execute(Click.java:14)
	at com.codeborne.selenide.commands.Click.execute(Click.java:11)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:139)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:86)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:62)
	at com.sun.proxy.$Proxy6.click(Unknown Source)
	at com.bnext.automation.po.esuite.sections.dashboard.DashboardTabContent.click_AddTile(DashboardTabContent.java:32)
	at test.DashboardsTest.testSwitchToFrame(DashboardsTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: unknown error: Sizzle is not defined
  (Session info: chrome=46.0.2490.86)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'BNH20067', ip: '10.70.100.11', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=C:\Users\SERHIY~1.KRY\AppData\Local\Temp\scoped_dir1856_14202}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.86, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 4d0d977f35e9485e4c47f123a18ec3d6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:537)
	at com.codeborne.selenide.Selenide.executeJavaScript(Selenide.java:430)
	at com.codeborne.selenide.impl.WebElementSelector.evaluateSizzleSelector(WebElementSelector.java:53)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:31)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)
	... 22 more
```

**Comment by saboteurserg** [comment] 2016-12-01 15:53
Code is the same

```
Configuration.selectorMode = Configuration.SelectorMode.Sizzle;
Selenide.switchTo().frame(iframeIndex);
$("[id='add-tile-btn']").click();
```

I created simple html with iframe... it's working... probably something wrong with the page I run this test on.. Can't give you a link because it's in internal network...   

when i change selector mode to CSS everything works fine.
Configuration.selectorMode = Configuration.SelectorMode.CSS;

**Comment by BorisOsipov** [comment] 2016-12-02 10:36
@saboteurserg thank you for details. Nevertheless, I still have no idea what's going on.

**Comment by asolntsev** [comment] 2019-07-03 21:25
@saboteurserg I am closing the issue as we could not reproduce it. 
As long as I see in `com.codeborne.selenide.impl.WebElementSelector` source, it injects Sizzle.js every time you call `$`, so I don't see how this bug could happen.

**Closed by asolntsev** 2019-07-03 21:25 UTC
Labels: cannot preproduce
