### ISSUE TITLE
Cannot visible empty span tag

### ISSUE THREAD

**Issue by jca02266** [selenide/selenide#988] opened 2019-10-07 23:30 UTC
## The problem

I will following the selenide test whether span is visible or not.

```
$(byXpath("//span[@id='test']")).shouldBe(visible)
```

Following tag is visible. (it has only one space in inner text)
```html
<span id="test"> </span>
```

But, next is not. (empty text)
```html
<span id="test"></span>
```

This is why?

## Tell us about your environment
* **Selenide Version:** 5.3.1
* **Chrome\Firefox\IE Version:** Chrome 77.0.3865.90
* **Browser Driver Version:**  77.0.3865.40
* **Selenium Version:** 3.141.59
* **OS Version:** Windows 10 1803

## Details

error message

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.257 sec <<< FAILURE!
test(sample.TestSelenide)  Time elapsed: 11.164 sec  <<< FAILURE!
com.codeborne.selenide.ex.ElementShould: Element should be visible {By.xpath: //span[@id='test_failure']}
Element: '<span id="test_failure" displayed:false></span>'
Actual value: visible:false
Screenshot: file:/C:/workspace/src/selenide_sample/build/reports/tests/1570490747378.0.png
Page source: file:/C:/workspace/src/selenide_sample/build/reports/tests/1570490747378.0.html
Timeout: 4 s.
        at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:72)
        at com.codeborne.selenide.commands.Should.execute(Should.java:24)
        at com.codeborne.selenide.commands.Should.execute(Should.java:10)
        at com.codeborne.selenide.commands.Commands.execute(Commands.java:145)
        at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
        at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
        at com.sun.proxy.$Proxy5.shouldBe(Unknown Source)
        at sample.TestSelenide.test(TestSelenide.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

10 08, 2019 8:25:47 午前 com.codeborne.selenide.drivercommands.CloseDriverCommand run
情報: Close webdriver: 19 -> ChromeDriver: chrome on XP (3adad5d9fdb85f7cb7fcd4f74dee1826)

Results :

Failed tests:   test(sample.TestSelenide): Element should be visible {By.xpath: //span[@id='test_failure']}(..)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

## Code To Reproduce Issue [ Good To Have ]

* selenide_sample/test.html

```
<!DOCTYPE html>

<html>
    <span id="test_pass"> </span>
    <span id="test_failure"></span>
</html>
```

* selenide_sample/pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>sample</groupId>
    <artifactId>selenide_sample</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Selenium Sample</name>
    <description></description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.test.skip>false</maven.test.skip>
        <!-- <selenium.version>4.0.0-alpha-3</selenium.version> -->
        <!-- <selenide.version>5.2.8</selenide.version> -->
        <selenium.version>3.141.59</selenium.version>
        <selenide.version>5.3.1</selenide.version>
    </properties>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/junit/junit -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <!-- <scope>test</scope> -->
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-support -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>${selenide.version}</version>
            <!-- <scope>test</scope> -->
        </dependency>
    </dependencies>
</project>
```

* selenide_sample/src/test/java/sample/TestSelenide.java

```
package sample;

import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Selectors.*;

import org.openqa.selenium.By;

import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;

import static org.junit.Assert.assertTrue;

import org.junit.Before;
import org.junit.Test;

public class TestSelenide {

    @Before
    public void setUp() throws Exception {
        Configuration.browser = WebDriverRunner.CHROME;
//        Configuration.headless = false;
//        System.setProperty("webdriver.chrome.driver", "./lib/chromedriver.exe");
//        System.setProperty("chromeoptions.args", "--disable-infobars");
//        Configuration.startMaximized = false;
//        Configuration.browserSize = "1100x768";
//        Configuration.holdBrowserOpen = true;
//        Configuration.fastSetValue = true;
//        Configuration.selectorMode = SelectorMode.Sizzle;
    }

    @Test
    public void test() throws Exception {
        open("file:///PLEASE OVERWRITE EXISTING PATH/test.html");

        $(byXpath("//span[@id='test_pass']")).shouldBe(visible);       // pass
        $(byXpath("//span[@id='test_failure']")).shouldBe(visible);    // failure
    }
}
```

**Comment by rosolko** [comment] 2019-10-08 06:42
@jca02266 By the way based on logs - when selenium is looking for this element it fetch it like an invisible: `<span id="test_failure" displayed:false></span>'`, because of `displayed:false`, can you please intercept your test execution and manually check this items for properties?

**Comment by jca02266** [comment] 2019-10-08 07:50
I think the "displayed:false" is added by Selenium or WebDriver (not HTML).
My problem is why this is added on empty span tag.

**Comment by rosolko** [comment] 2019-10-08 10:59
@jca02266 But selenide honors selenium behavior, so the problem is on selenium side

**Comment by jca02266** [comment] 2019-10-13 00:11
I found a closed issue at SeleniumHQ/selenium: https://github.com/SeleniumHQ/selenium/issues/6058.
I think related about this issue.

By the way, the "displayed:false" is added by Selenide. It is means "!isDisplayed()".

https://github.com/selenide/selenide/blob/63d2c0f1c3e4e4dc20a776c9da831883ff2e23b1/src/main/java/com/codeborne/selenide/impl/Describe.java#L171

**Comment by asolntsev** [comment] 2019-10-28 23:47
@jca02266 Thank you for the information. Closing the issue.

**Closed by asolntsev** 2019-10-28 23:47 UTC
