### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory selenide-netty-client-factory

### ISSUE THREAD

**Issue by lizongjian** [selenide/selenide#1986] opened 2022-10-14 06:11 UTC
hi:
    I'm normal in IDEA，run errors after maven package!
    
    public static void main(String[] args) {
        TestNG testNG = new TestNG();
        Class[] arr = new Class[]{Login.class};
        testNG.setTestClasses(arr);
        testNG.run();
    }

    Login.java :
    @Test
    public void test1(){
        Selenide.open("https://www.baidu.com");
    }

  maven package == > java -jar xx.jar

Caused by: java.lang.IllegalArgumentException: Unknown HttpClient factory selenide-netty-client-factory
	at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:57)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor$DefaultClientFactoryHolder.<clinit>(HttpCommandExecutor.java:58)
	... 50 more

pom :

   <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>6.7.4</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
           
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>com.XX.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>assembly</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by asolntsev** [comment] 2022-10-15 14:55
Duplicate of https://github.com/selenide/selenide/issues/1985

**Closed by asolntsev** 2022-10-15 14:55 UTC
Labels: not a bug, duplicate
