### ISSUE TITLE
Feature Request: SelenideDriver should implements AutoCloseable

### ISSUE THREAD

**Issue by evpl** [selenide/selenide#1416] opened 2021-02-22 11:49 UTC
Hi. I am using the RAII idiom in my tests. Also I have extended the `SelenideDriver` class to use with a try-with-resources statement. 
I did it because of the `void close ()` method of `SelenideDriver` conforms to the `AutoCloseable` interface (unlike WebDriver with `void close()` and `void quit()` methods - [selenium issue](https://github.com/SeleniumHQ/selenium/pull/650)).
```
public class AutoClosableSelenideDriver extends SelenideDriver implements AutoCloseable {

    public AutoClosableSelenideDriver(Config config) {
        super(config);
    }

    public AutoClosableSelenideDriver init() {
        this.open();
	return this;
    }
}
```
```
try (AutoClosableSelenideDriver driver = new AutoClosableSelenideDriver(config).init()) {
	// actions
}
```

It works fine. How about adding this feature to Selenide? I suggest the following actions:

1) `SelenideDriver` implements `AutoCloseable`

2) I agree that initialization shouldn't happen in the constructor, it should run with a call to a specific method. But my `AutoClosableSelenideDriver init ()` method just wraps the `void open ()` method call. I think that every `open ()` method that returns `void` should return `SelenideDriver` instance. It will be convenient to use:

```
try (SelenideDriver driver = new SelenideDriver(config).open()) {
	// actions
}
```

**Comment by asolntsev** [comment] 2021-02-22 16:40
@evpl Hi. Initially, I don't understand what problem we are really solving. 
Selenide code is written so that you don't need to explicitly close webdriver. Selenide will close it automatically. 
Moreover, in most cases you don't need to use `SelenideDriver` explicitly. It was intended only for rare cases when you need to open 2 browsers in the same thread (see https://selenide.org/2018/10/10/selenide-5.0.0/).

**Comment by evpl** [comment] 2021-02-25 15:14
@asolntsev Thank you. I've read the source code and now I see. You are using ShotdownHook to close the driver. Closing did not work for me a couple of times, apparently due to the incorrect program termination. Maybe you can add a short description to the javadoc or link to a blog with an explanation.

**Comment by asolntsev** [comment] 2021-02-25 15:43
@evpl Sure, adding this info to documentation is a good idea. 
Can you suggest a good place in site/github/wiki/docs where you probably would easier find it?

**Closed** 2021-03-11 09:55 UTC
Labels: question, waiting-for-author
