### ISSUE TITLE
Problem with checking download file with filter then installed custom download path. 

### ISSUE THREAD

**Issue by Spartan1221** [selenide/selenide#2773] opened 2024-06-28 08:08 UTC
## The problem
Problem with checking download file with filter then installed custom download path. 

## Details
I set custom download path (/custom/folder) for chrome browser by setting prefs on WebDriver by experimentalOption. 
And then I am downloading file with DownloadFileToFolder.download using  DownloadOptions.using(FOLDER) 
I have error with checking downloaded file because selenide looking my file in /custom/folder/timestamp.
Need solution for setting custom download path and checking file with filter after it's downloaded.
By default selenide add download path(depends on Configuration.downloadsFolder) in default experimentalOptions. And then we set custom experimentalOptions it's all replacing by custom options. There's no way to configurate corectly downloading path. When we setting path "/custom/folder" browser downloading files in "/custom/folder", but selenide looking files in "/custom/folder/timestamp"

## Tell us about your environment
Selenide Version 7.3.3
Google Chrome 126.0.6478.127 (Official Build) (arm64) 
OS macOS Version 14.1.1 (Build 23B81)

**Comment by asolntsev** [comment] 2024-06-28 08:15
@Spartan1221 The solution is simple: don't set custom download path (/custom/folder). Don't put it to experimentalOptions.
Then everything works out-of-the-box. 

If you really need to change the folder to download files, set `Configuration.downloadsFolder = "custom/folder"`.

**Comment by Spartan1221** [comment] 2024-06-28 09:07
It's not working for me.   
Originally I'm setted additional permissions(for copyboard) through experimentalOptions and after that download stop working. 
I'd try to solve this problem by setting custom download folder in experimentalOptions and find new problem that selenide can't work like that.

**Comment by Spartan1221** [comment] 2024-06-28 09:14
I solved problem with copyboard settings by setting options in another way (System.setProperty("chromeoptions.prefs", options)), but it was really hard to find out corect way to set values for that way.
I'll be glad to have configuring through experimentalOptions.
Maybe there could be merge option for it.

**Comment by Spartan1221** [comment] 2024-06-28 09:14
@asolntsev

**Comment by asolntsev** [comment] 2024-06-28 10:26
Can you show the code that setups experimentalOptions?

**Comment by Spartan1221** [comment] 2024-06-28 10:58
Something like that:
ChromeOptions()
            .setExperimentalOption("prefs", "profile.content_settings.exceptions.clipboard="{'[*.],*':{'last_modified':'12325564','setting':1}}"")

**Comment by asolntsev** [comment] 2024-07-04 19:36
@Spartan1221 The problem is that you set `ChromeOptions.setExperimentalOption("prefs", YOUR_VALUE)`.
And Selenide also sets `ChromeOptions.setExperimentalOption("prefs", SELENIDE_VALUE)`.
And you override the Selenide's prefs (including the downloads folder).

**Comment by asolntsev** [comment] 2024-07-25 07:55
@Spartan1221 In PR https://github.com/selenide/selenide/pull/2793, we will merge "your prefs" with "selenide prefs". 
Will be released soon in Selenide 7.4.0

**Closed** 2024-07-25 20:38 UTC
Labels: downloading files
