### ISSUE TITLE
Cannot start driver after upgrade from 5.12.2 to 5.14.2

### ISSUE THREAD

**Issue by pgarbocz** [selenide/selenide#1265] opened 2020-09-07 10:57 UTC
## The problem
After the upgrade from Selenide 5.12.2 to 5.14.2, the chromedriver cannot start. I'm able to start it myself, but something's wrong when it's started by the code. I tried the versions between and it stopped working for me from 5.13.0. When I'm back to 5.12.2, it starts working immediately.

Is there some new property I have to set or my code that starts the webdriver is outdated?

## Details
I'm getting these errors:
`Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 2464
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Failed to redirect stderr to log file.
Unable to initialize logging. Exiting...
Sep 07, 2020 12:36:11 PM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)`

`org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'FP-PC2721', ip: '10.0.1.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: SelenideDriver
selenide.url: https://fp1.gi-de.future-processing.com/
selenide.baseUrl: https://fp1.gi-de.future-processing.com/
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:53)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:76)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:54)
	at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:50)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:136)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:128)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89)
	at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:61)
	at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:180)
	at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
	at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
	at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:76)
	at com.codeborne.selenide.Selenide.open(Selenide.java:48)
	at commons.PortalNavigator.goToStartPage(PortalNavigator.java:21)
	at tests.Management.PoliciesTests.setUp(PoliciesTests.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at
......
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:2464/status] to be available after 20001 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:197)
	... 113 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:155)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 114 more`

## Tell us about your environment
* **Selenide Version**: 5.14.2
* **Chrome**:  85.0.4183.83 (Official Build) (64-bit)
* **Browser Driver Version**: ChromeDriver 85.0.4183.87
* **Selenium Version**: 3.141.59
* **OS Version**: Windows 10

## Code To Reproduce Issue
In terms of starting webdriver, here's the code:
```java
@BeforeAll
public static void beforeUITests() {
        setBrowserDrivers();

        baseUrl = getProperty("baseUri");
        browser = getProperty("browserType");
        browserSize = getProperty("browserSize");
        startMaximized = true;
        fastSetValue = true;
        holdBrowserOpen = false;
        timeout = getIntProperty("implicitlyWaitTimeSeconds") * 1000;
        reportsFolder = "build/reports/tests-results";
        headless = getBooleanProperty("headless");
        screenshots = getBooleanProperty("screenshots");

        clearBrowserCache();
    }

    private static void setBrowserDrivers() {

        String chromeDriverProperty = "chromeDriverLinuxPath";
        String ffDriverProperty = "ffDriverLinuxPath";

        if (SystemUtils.IS_OS_WINDOWS) {
            chromeDriverProperty = "chromeDriverWindowsPath";
            ffDriverProperty = "ffDriverWindowsPath";
        }

        setProperty("webdriver.chrome.driver", getPathProperty(chromeDriverProperty));
        setProperty("webdriver.firefox.driver", getPathProperty(ffDriverProperty));
        setProperty("webdriver.gecko.driver", getPathProperty(ffDriverProperty));
    }
```

**Comment by BorisOsipov** [comment] 2020-09-07 11:37
Hi @pgarbocz 

First, can you setup logging accoirding https://github.com/selenide/selenide/wiki/slf4j and share with us gist\pastebin of full test log? It will help invistigate issue.

Second, Can you try workaround `Configuration.reportsFolder = System.getProperty("java.io.tmpdir");` - it should help.

**Comment by pgarbocz** [comment] 2020-09-07 11:53
> Second, can you try workaround Configuration.reportsFolder = System.getProperty("java.io.tmpdir"); - it should help.
Yes, it's working.

> First, can you setup logging accoirding https://github.com/selenide/selenide/wiki/slf4j and share with us gist\pastebin of full test log? It will help invistigate issue.

```
[Test worker] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 11 - let's create a new webdriver
[Test worker] INFO com.codeborne.selenide.impl.FileHelper - Creating folder: C:\code\e2e-tests\build\downloads\1599478926230_38420_11
[Test worker] INFO com.codeborne.selenide.webdriver.AbstractDriverFactory - Write webdriver logs to: C:\code\e2e-tests\build\reports\tests-results\webdriver.1599478926330_38420_11.log
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 19695
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Failed to redirect stderr to log file.
Unable to initialize logging. Exiting...
Sep 07, 2020 1:42:26 PM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

The downloads folder is created, but the reports with tests-results is not. Maybe the issue is that the webdriver log in my case should be saved deeper in the solution.
It's trying to save it in `e2e-tests\build\reports\`
but in my case it should be `gd-gui-tests\build\reports\tests-results` where currently results are being stored.

**Comment by BorisOsipov** [comment] 2020-09-07 12:19
Minimal reproducable example
```
        Configuration.reportsFolder = "build\reports\tests-results";
        open("https://www.google.com");
```

Weird that console log in IDEA doesn't show correct output
```
[main] DEBUG com.codeborne.selenide.webdriver.ChromeDriverFactory - Chrome options: Capabilities {acceptInsecureCerts: true....}
eports	ests-results
eports	ests-results
eports	ests-results\webdriver.1599480867397_12664_1.log
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 25712
```

**Comment by asolntsev** [comment] 2020-09-07 15:14
@BorisOsipov I cannot reproduce the issue. Selenide creates the folder and opens the browser.

**Comment by BorisOsipov** [comment] 2020-09-07 15:30
Seems only windows issue. Windows path must not contains `\r` `\t` symbols

**Comment by asolntsev** [comment] 2020-09-07 16:00
Fixed by https://github.com/selenide/selenide/commit/94ece98fe17fd312ada42a45b297640fb331ad1f

**Closed by asolntsev** 2020-09-07 16:00 UTC
Labels: bug 🐛, help wanted

**Comment by pgarbocz** [comment] 2020-09-10 10:23
@asolntsev It doesn't really fix the issue and I couldn't find a workaround other than changing folder names.

I tried to escape the  \r and \t but it doesn't change a thing:
`reportsFolder = "build\\/reports\\/tests-results";`
`reportsFolder = "build\\/\\reports\\/\\tests-results";`

When I changed it to:
`reportsFolder = "build/breports/btests-results";`
then I started working.

Is there a way I could escape these characters so I don't change the folder names?

**Comment by asolntsev** [comment] 2020-09-10 10:32
@pgarbocz How did you check that commit 94ece98 didn't fix the issue? 
Selenide 5.15.0 (which will contain the fix) is not released yet. Apparently, you are using Selenide 5.14.2 which doesn't contain this fix. 

And I guess you are escaping in incorrectly. Try one of these variants:
1. `reportsFolder = "build\\reports\\tests-results";`
2. `reportsFolder = "build/reports/tests-results";`

**Comment by pgarbocz** [comment] 2020-09-10 10:37
> And I guess you are escaping in incorrectly. Try one of these variants:
reportsFolder = "build\\reports\\tests-results";
reportsFolder = "build/reports/tests-results";

I tried these ones as well - didn't work.

> How did you check that commit 94ece98 didn't fix the issue?
Selenide 5.15.0 (which will contain the fix) is not released yet. Apparently, you are using Selenide 5.14.2 which doesn't contain this fix.

I assumed it seeing the change, so maybe I'm wrong but from what I see it doesn't change the way of creating folder or handling paths, it just changes the way that the error is thrown.

**Comment by BorisOsipov** [comment] 2020-09-10 10:42
@pgarbocz can you double check `reportsFolder = "build\\reports\\tests-results";` ?

it works on my side, see screen.

![image](https://user-images.githubusercontent.com/6514276/92719102-57e69180-f36b-11ea-89f6-7caee6a023f1.png)

**Comment by pgarbocz** [comment] 2020-09-10 10:47
@BorisOsipov 
Double checked and it doesn't work for me.

I added again "b" before between "/" and "r" and "t" and then it started working.
`reportsFolder = "build\\breports\\btests-results";`

**Comment by BorisOsipov** [comment] 2020-09-10 11:30
Can you share screen with execution results this code:

```

    @Test
    public void test() throws Exception {
        String reportPath = "build\\reports\\tests-results";
        File folder = new File(reportPath);
        System.out.println(folder.getCanonicalFile());
    }

```

**Comment by pgarbocz** [comment] 2020-09-10 11:43
@BorisOsipov 
![image](https://user-images.githubusercontent.com/54275023/92724903-a2680e00-f36b-11ea-83c4-6d751bfc2c52.png)

**Comment by BorisOsipov** [comment] 2020-09-10 12:25
I have no clue what's going on...
