### ISSUE TITLE
Deadlock in static initialization

### ISSUE THREAD

**Issue by cocorossello** [selenide/selenide#2372] opened 2023-07-18 11:45 UTC
## The problem
I can see that a very few times my test suite becomes totally locked for an unlimited time until I abort it. 

The test suite opens several threads in parallel. Looking at a thread dump:

```
"ForkJoinPool-1-worker-1" #53 [2764313] daemon prio=5 os_prio=0 cpu=929.57ms elapsed=224.82s tid=0x00007faaf1967000 nid=2764313 waiting on condition  [0x00007faac554c000]
 java.lang.Thread.State: RUNNABLE
at com.codeborne.selenide.Condition.<clinit>(Condition.java:149)
**- waiting on the Class initialization monitor for com.codeborne.selenide.conditions.And**
at com.tr2.test.endtoend.selenium.base.SeleniumUtils.loginAndGoTo(SeleniumUtils.java:95)
....
"ForkJoinPool-1-worker-2" #59 [2764520] daemon prio=5 os_prio=0 cpu=614.29ms elapsed=212.44s tid=0x00007faa1c4a1610 nid=2764520 waiting on condition  [0x00007faac7068000]
 java.lang.Thread.State: RUNNABLE
at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsClickable(WebElementSource.java:173)
**- waiting on the Class initialization monitor for com.codeborne.selenide.Condition**
at com.codeborne.selenide.commands.Click.findElement(Click.java:46)
at com.codeborne.selenide.commands.Click.execute(Click.java:28)
at com.codeborne.selenide.commands.Click.execute(Click.java:21)
at com.codeborne.selenide.commands.Commands.execute(Commands.java:162)
at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:132)
at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:84)
at jdk.proxy2.$Proxy24.click(jdk.proxy2/Unknown Source)
at com.tr2.test.endtoend.selenium.page.HomePage.lambda$start$54(HomePage.java:640)
...
"ForkJoinPool-1-worker-4" #61 [2764522] daemon prio=5 os_prio=0 cpu=518.60ms elapsed=212.44s tid=0x00007faa8001d6f0 nid=2764522 waiting on condition  [0x00007faac6058000]
 java.lang.Thread.State: RUNNABLE
at com.tr2.test.endtoend.selenium.page.DestinationsPage.checkArrival(DestinationsPage.java:76)
**- waiting on the Class initialization monitor for com.codeborne.selenide.Condition**
at com.tr2.test.endtoend.selenium.page.DestinationsPage.checkArrival(DestinationsPage.java:68)
```

So, they are locked at some point in selenide, I don't really know where or why.

I think I can workaround doing some static initialization myself, before the multithreading kicks in, but I'm not sure.

Do you have any clue at where I can look? It only happened two times

## Tell us about your environment
* **Selenide Version**:  6.16.0
* **Chrome\Firefox\IE Version**:  111.0
* **Selenium Version**: selenium/standalone-chrome:4.8.3-20230404
* **OS Version**: Ubuntu

**Comment by asolntsev** [comment] 2023-07-18 21:12
I think I know what's the reason.
It's called "Static initialization deadlock" or "Class Initialization Deadlock". 
I never experienced it with Selenide, but got it once in Play1 framework. 

The reason is that classes `Condition` and `And` depend on each other, and some static fields of `Condition` do use class `And`. 

The right solution would be to move all static fields from `Condition` to some other class - say, `Conditions`. 
But it would cause a huge backward incompatibility. :) 
Not sure if it's worth it.

**Comment by cocorossello** [comment] 2023-08-03 07:54
I haven't seen the error since I put this in our ChromeDriverProvider class, wich is executed before multithread kicks in.

```
    static {
        Condition.and("avoid static initialization deadlock", Condition.cssClass("whatever"), Condition.attribute("whatever", "whatever")); //workaround for static initizaliations deadlock https://github.com/selenide/selenide/issues/2372
    }
```

It's a bit dirty, but...

**Comment by asolntsev** [comment] 2023-08-29 17:20
@cocorossello I am not sure it really solves the problem. At least I don't see a reasonable explanation why it should solve.

I rather think that this problem is so hard to reproduce that you never know if your change helped, or it's just a coincidence.

**Comment by cocorossello** [comment] 2023-08-30 20:58
Great!

I'm not aware of using directly those, the selenium codebase is more than 200 kotlin/java classes right now.

I have some custom conditions like:

```
public class CssClasses extends Condition {
    private final String[] expectedCssClasses;

    public CssClasses(String... expectedCssClasses) {
        super("css classes");
        this.expectedCssClasses = expectedCssClasses;
    }

    public static Condition cssClasses(String... cssClasses) {
        return new CssClasses(cssClasses);
    }

    @Override
    public boolean apply(Driver driver, WebElement element) {
        String actualCssClasses = element.getAttribute("class");
        return actualCssClasses != null && contains(actualCssClasses.split(" "), expectedCssClasses);
    }
...
```
(BTW, this one just doesn't make sense, I just deleted it).

The deadlock may come from this kind of custom conditions

**Comment by asolntsev** [comment] 2023-09-03 15:00
It will be fixed in https://github.com/selenide/selenide/pull/2453,
but I think we will release it as Selenide 7.0.0 in November 2023 (since it's a remarkable backward-incompatible change).

**Closed as completed** 2023-10-18 18:10 UTC
Labels: low priority, bug 🐛, has pr
