### ISSUE TITLE
Add aliases for $ and $$ for Kotlin

### ISSUE THREAD

**Issue by nbdnnm** [selenide/selenide#865] opened 2018-11-19 12:15 UTC
Hello,

Kotlin doesn't support $ and $$ without \` \`, so how about to add aliases, like S and SS or something else?

**Comment by d-astanin** [comment] 2018-11-19 13:33
For your kotlin project you can use code like that
```
fun s(locator: String): SelenideElement {
    return Selenide.`$`(locator)
}

fun ss(locator: String): ElementsCollection {
    return Selenide.`$$`(locator)
}
```

**Comment by vinogradoff** [comment] 2018-11-19 13:36
…which looks ugly


I would also support aliases, e.g. S/SS or s/ss or something else.

Viele Grüße

Alexei Vinogradov

On 19. November 2018 at 13:15:38, nbdnnm (notifications@github.com) wrote:

The problem

Briefly describe the issue you are experiencing (or the feature you want to
see added to Selenide).
Tell us what you were trying to do and what happened instead.
Details

If necessary, describe the problem you have been experiencing in more
detail.
Tell us about your environment

   - *Selenide Version:*
   - *Chrome\Firefox\IE Version:*
   - *Browser Driver Version:*
   - *Selenium Version:*
   - *OS Version:*

Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/selenide/selenide/issues/865>, or mute the thread

**Comment by evgeny-tumashchick** [comment] 2018-11-20 11:35
Hi folks, actually I use Selenide in my Kotlin project.
I call mentioned aliases like this:
`$`(fieldLocator)   / `$x`(fieldLocator)
`$$`(fieldLocator)   / `$$x`(fieldLocator)

**Comment by jkromski** [comment] 2018-11-20 13:30
wouldn't be better to follow naming from SelenideElement which is `find` for $?

**Comment by vinogradoff** [comment] 2018-11-20 13:42
Not quite. $() doesn't actually do any search yet. Find is misleading then.

Viele Grüße

Alexei Vinogradov

**Comment by jkromski** [comment] 2018-11-20 13:52
Interface says it is the same
```java
/**
   * ATTENTION! This method doesn't start any search yet!
   * Same as {@link #find(String)}
   * @see com.codeborne.selenide.commands.Find
   */
  SelenideElement $(By selector);
```
```java
/**
   * ATTENTION! This method doesn't start any search yet!
   * Same as {@link #find(String)}
   * @see com.codeborne.selenide.commands.Find
   */
  SelenideElement find(By selector);
```

**Comment by jkromski** [comment] 2018-11-20 13:56
```java
/**
   * Locates the first element matching given CSS selector
   * ATTENTION! This method doesn't start any search yet!
   * @param cssSelector any CSS selector like "input[name='first_name']" or "#messages .new_message"
   * @return SelenideElement
   */
  public static SelenideElement $(String cssSelector) {
    return getSelenideDriver().find(cssSelector);
  }
```
find is original method, $ is only an alias for it, so I would add find and findAll into Selenide class.

**Comment by vinogradoff** [comment] 2018-11-20 14:17
I know:) it is not perfect, because findElement() in Selenium start search,
so many assume find() in Selenide start search too, but it doesn't. Legacy
name :)

Viele Grüße

Alexei Vinogradov

**Comment by jkromski** [comment] 2018-11-20 15:14
I don't get why this is a problem. Selenide has proxy elements, why do you care that find/$ does not find immediately?
Selenide solve that problem of immediate searching, which is good.
From what I see, this ticket is for adding better support for Kotlin. 

find()/findAll() in Selenide Class will provide that support, without introducing brand new alias as it exists already in SelenideElement
If we would add s/ss then we end up with find/findAll/$/$$/s/ss in SelenideElement and s/ss/$/$$ in Selenide which is not consistent.

does it make sense?

**Comment by vinogradoff** [comment] 2018-11-20 15:40
it is not a *problem*. I just don't like "find" to be part Selenide DSL if it doesn't search. It is already partly (in SelenideElement) due to historical reasons. I more like introducing s/ss (or whatever new alias) and deprecating find/findAll.

**Comment by rosolko** [comment] 2018-11-20 15:42
As described before, if you want to use your own aliases just implement on your side.
Ref: https://github.com/selenide/selenide/issues/865#issuecomment-439894042

**Comment by vinogradoff** [comment] 2018-11-20 16:59
From point of view of Selenide user, I would not want to know about lazy evaluation or other patterns used **inside of** Selenide, just well-working and readable functions :)

**Comment by jkromski** [comment] 2018-11-22 16:55
my view:
- add `find`, `findX`, `findAll`, `findAllX` methods in Selenide class (going further I would deprecate `x` methods as each xpath starts with `/` so finding if this is xpath could be done on SelenideDriver level)
- deprecate getElement* methods as they don't follow naming convention from SelenideDriver or SelenideElement

**Comment by asolntsev** [comment] 2018-12-07 22:53
@jkromski We are still arguing there :)

**Comment by asolntsev** [comment] 2019-01-12 22:42
Implemented in https://github.com/selenide/selenide/pull/870
Will be released in Selenide 5.2.0

@jkromski Thank you for the contribution!

**Closed by asolntsev** 2019-01-12 22:42 UTC
Labels: feature

**Comment by yashaka** [comment] 2019-07-13 10:36
@asolntsev, probably it would be consistent to have the same methods in SelenideDriver...

**Comment by yashaka** [comment] 2019-07-13 19:03
another thing regarding consistency...
we have `$x`, but we don't have `elementx`... 

just `elementx` sounds awkward o_O... 

maybe we should consider to make `$(String)` smart enough to distinguish css from xpath selectors... Actually it's not hard to do this. This would be pretty handy in usage, and we will have less weird method names like `$$x` :)

**Comment by BorisOsipov** [comment] 2019-07-13 19:06
>maybe we should consider to make $(String) smart enough to distinguish css from xpath selectors... Actually it's not hard to do this. This would be pretty handy in usage, and we will have less weird method names like $$x :)

agree. it isn't hard to implement

**Comment by yashaka** [comment] 2019-07-13 19:12
have just noticed one more consistency thing... 

if we have $ and element in Selenide.*, and we will have them in SelenideDriver#*, then it will be consistent to have them both in SelenideElement#*... Yeah, it will be awkward a bit because we already have SelenideElement#find :(, so I am not sure... Ideally would be good to not have `find`... But... Yet we can deprecate it:) Maybe I am too nerdy, of course:)

**Comment by asolntsev** [comment] 2019-07-14 21:10
@yashaka I personally don't find method `$x` really usable. 
I think `element(By.xpath("..."))` is good enough, and don't see really much sense in inventing some better alternative for it. Sure, `elementx` doesn't make sense at all. 

@BorisOsipov @yashaka Yes, the idea to make `$(String)` smart enough to support both CSS selectors and XPath was in air several years ago. But folks said that Thucydides framework already had such a feature, and it didn't always work well. They didn't recommend to do it. 

Probably we can do it better, but it would be good to investigate what problems Thucydides had.

**Comment by asolntsev** [comment] 2019-07-14 21:18
>  Ideally would be good to not have `find`... But... Yet we can deprecate it:)

I personally like name `find`. I don't see any problems with the fact that it doesn't search immediately - it's just lazy loading. 

About having `element` method in `SelenideElement` - it seems to be a bad naming.  

Look: 
* `element(".error").shouldNot(exist)` - sounds good
* `element("table.one").element("tr.two").should(exist)` - does not. 

Probably name `child` would be reasonable? 
* `element("table.one").child("tr.two").should(exist)`?

**Comment by yashaka** [comment] 2019-07-14 22:53
`child` is bad, because we actually can do something like:
`element("table.one").child(byXpath("..")).should(exist)`, or "./followingSibling:input[...]"...

For my taste, this:

`element("table.one").element("tr.two").should(exist)`
is ok:)

just a sequential locating of elements... 

regarding `find` and "lazy loading" - lazyness is ok for "tech programming language", but if we think about selenide as "user oriented tool", then I would hide such technical things and reveal only "user-oriented behavioural" API... 

That's why I like more Selenide.element than Selenide.$ or Selenide.find. 
Yet, being a nerd:), for me it's more important to be consistent than "user-oriented". This means that probably between:

1. Selenide.element, SelenideElement#find
2. Selenide.find, Selenide#find
3. Selenide.element, SelenideElement#element

I would choose 2 over 1 if I can't choose 3 :)
